// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKRNBHxBuKjNr3PiLIlr1k0mrnHnIrYfg',
    appId: '1:850866194355:web:8ace63853eaedacc532dc6',
    messagingSenderId: '850866194355',
    projectId: 'cocktailbarapp-d2c08',
    authDomain: 'cocktailbarapp-d2c08.firebaseapp.com',
    storageBucket: 'cocktailbarapp-d2c08.appspot.com',
    measurementId: 'G-DX3LFX4PY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqO7i2TguN5A5iLALIHo8hDczbs_CGtzk',
    appId: '1:850866194355:android:cfb49c8e2e77dd26532dc6',
    messagingSenderId: '850866194355',
    projectId: 'cocktailbarapp-d2c08',
    storageBucket: 'cocktailbarapp-d2c08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyxb_5S8ZFPYmSDQfYW0HLIzAvmiF5v-c',
    appId: '1:850866194355:ios:04c88bf3fa1dc0de532dc6',
    messagingSenderId: '850866194355',
    projectId: 'cocktailbarapp-d2c08',
    storageBucket: 'cocktailbarapp-d2c08.appspot.com',
    iosBundleId: 'com.example.cocktailbarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyxb_5S8ZFPYmSDQfYW0HLIzAvmiF5v-c',
    appId: '1:850866194355:ios:04c88bf3fa1dc0de532dc6',
    messagingSenderId: '850866194355',
    projectId: 'cocktailbarapp-d2c08',
    storageBucket: 'cocktailbarapp-d2c08.appspot.com',
    iosBundleId: 'com.example.cocktailbarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKRNBHxBuKjNr3PiLIlr1k0mrnHnIrYfg',
    appId: '1:850866194355:web:67295b4f455b49e5532dc6',
    messagingSenderId: '850866194355',
    projectId: 'cocktailbarapp-d2c08',
    authDomain: 'cocktailbarapp-d2c08.firebaseapp.com',
    storageBucket: 'cocktailbarapp-d2c08.appspot.com',
    measurementId: 'G-H53J2FQEJ7',
  );

}